spring:
  application:
    name: prometheus-01
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        #include: '*'
        include: [ "prometheus" ]
  endpoint:
    health:
      show-details: always # 显示详细的健康检查信息
  metrics:
    export:
      prometheus:
        enabled: true # Prometheus 可以通过按照 metrics 属性抓取应用的运行指标数据
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.9,0.99
      slo:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
      minimum-expected-value:
        http:
          server:
            requests: 1ms
      maximum-expected-value:
        http:
          server:
            requests: 1s
#    web:
#      client:
#        request:
#          autotime:
#            percentiles-histogram: true
#            percentiles: [0.5,0.9,0.99]