#spring:
#  data:
#    # Elasticsearch 配置项
#    elasticsearch:
#      cluster-name: elasticsearch # 集群名
#      cluster-nodes: 127.0.0.1:9300 # 集群节点
spring:
  elasticsearch:
    uris: 127.0.0.1:9200    # 不指定默认是 http://localhost:9200

