server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&allowPublicKeyRetrieval=true&useConfigs=maxPerformance&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      max-active: 5
      min-idle: 3
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filters: stat,log4j2
      # StatFilter
      filter.stat.enabled: true
      filter.stat.db-type: mysql
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 2000
      # Log4j2Filter
      filter.log4j2.enabled: true
      filter.log4j2.statement-create-after-log-enabled: false
      filter.log4j2.statement-close-after-log-enabled: false
      filter.log4j2.result-set-open-after-log-enabled: false
      filter.log4j2.result-set-close-after-log-enabled: false
  jackson:
    mapper:
      default-view-inclusion: true
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
      accept-single-value-as-array: true

mybatis:
  mapper-locations: classpath:**/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jwt:
  secret-key: rJ1lN9tP1rR2iX7hX1iO1wF9mW8aS2mAmV0JdNgw4tNtQvvEwapWZWRbsvS5b4r7g46C
  # 24 hours
  validity: 24h
