# 基于注册中心的动态路由
spring:
  cloud:
    gateway:
      routes:
        # 动态路由
        - id: route-service-echo-dynamic
#          uri: http://localhost:8081
          uri: lb://service-echo
          predicates:
            - Path=/service-echo/**
          filters:
            - RewritePath=/service-echo/(?<remaining>.*), /${remaining}   # 将 /service-echo 前缀剔除
        - id: route-service-time-dynamic
          uri: lb://service-time
          predicates:
            - Path=/service-time/**
          filters:
            - RewritePath=/service-time/(?<remaining>.*), /${remaining}   # 将 /service-time 前缀剔除
        - id: route-service-time-statistic
          uri: http://localhost:8082
          predicates:
            - Path=/time/**
      # 通过服务注册与发现,动态将服务名替换为服务节点地址
      discovery:
        locator:
          enabled: true                           # 是否开启，默认为 false
          lower-case-service-id: true
#          url-expression: "'lb://' + serviceId"   # 路由的目标地址的表达式，默认为 "'lb://' + serviceId"

    # Nacos 作为注册中心的配置项
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      discovery:
        namespace: ${NAMESPACE:dev}
        group: GATEWAY-SAMPLE