spring:
  redis:
    #password:
    database: 0
    cluster:
      # Redis 集群地址信息
      nodes:
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381
        - 127.0.0.1:26382
        - 127.0.0.1:26383
        - 127.0.0.1:26384
      # 获取失败 最大重定向次数
      max-redirects: 3
    #如果用以前的jedis，可以把下面的lettuce换成jedis即可
#    lettuce:
    jedis:
      pool:
        # 连接池最大连接数默认值为8
        max-active: 1000
        # 连接池最大阻塞时间（使用负值表示没有限制）默认值为-1
        max-wait: -1
        # 连接池中最大空闲连接数默认值为8
        max-idle: 10
        # 连接池中的最小空闲连接数，默认值为0
        min-idle: 10
