server:
  port: 8083

spring:
  # 数据源配置
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/boot-activiti?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
#    username: root
#    password: 123456
#  hikari:
#    pool-name: Retail_HikariCP
#    minimum-idle: 15 #最小空闲连接数量
#    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
#    maximum-pool-size: 25 #连接池最大连接数，默认是10
#    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
#    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
#    connection-test-query: SELECT 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boot-activiti?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/boot-activiti?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
        username: root
        password: 123456
      # 从库数据源
      slave:
        # 从数据源开关, 默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  # Activiti工作流引擎
  activiti:
    database-schema-update: true
#    database-schema-update: create-drop
    db-history-used: true
    history-level: full
    check-process-definitions: false
    deployment-mode: never-fail
    process-definition-location-prefix: classpath:/process/

logging:
  level:
    org.activiti.engine.impl.db: debug
